name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up SFML
        run: sudo apt-get update && sudo apt-get install -y libsfml-dev build-essential
        
      - name: Build and run
        run: make
